### ISSUE TITLE
How to run the appp as webapp?

### ISSUE THREAD

**Issue by anmol26s** [starsoccer/cryptotithe#8]
Hi
Thanks for doing the app.
How can the app be ran as web-app?

**Comment by starsoccer** [comment]
Good question so to run this as a webapp you can simple run `npm run web` as per the package.json file, https://github.com/starsoccer/cryptotithe/blob/master/package.json#L8 assuming you already ran `npm install`

**Comment by anmol26s** [comment]
I am getting error. I run am trying to run over a server.

```
npm run web

> cryptotithe@0.4.1 web /root/cryptotithe
> npm run build && start ./index.html


> cryptotithe@0.4.1 build /root/cryptotithe
> tsc -p configs/tsconfig.json && browserify ./react.js -o ./bundle.js -u ./data.json --im

sh: 1: start: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! cryptotithe@0.4.1 web: `npm run build && start ./index.html`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the cryptotithe@0.4.1 web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-07T22_33_50_942Z-debug.log

```

**Comment by starsoccer** [comment]
Hmm interesting start is supposed to just automatically start the web browser for you. I will look into this. In the mean time you can simply go to the folder and open the index.html file. After building the index.html file should function like normal

**Comment by starsoccer** [comment]
I just pushed some changes so opening the web app should now be done using `opn-cli`. Try pulling down the new code and let me know if it still doesnt work. You will have to run `npm install` again though.

**Comment by anmol26s** [comment]
I still get error:
```
npm run web
npm ERR! missing script: web

npm ERR! A complete log of this run can be found in:

```

**Comment by starsoccer** [comment]
Can you try running `npm install --dev` and then `npm run web`
